[package]
name = "endsong_ui"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4"
chrono-tz = "0.8"
endsong = {path = ".."}
rustyline = { version = "12.*", features = ["derive"] }
unicode-width = "0.1.10"
plotly = "0.8"
itertools = "0.11.0"
