on: [push, pull_request]

name: Continuous integration

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo check && cd endsong_web && cargo check && cd ../endsong_ui && cargo check && cd endsong_macros && cargo check

  test:
    name: Test Suite
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo test --all-features && cd endsong_web && cargo test --all-features && cd ../endsong_ui && cargo test --all-features && cd endsong_macros && cargo test --all-features

  fmt:
    name: Rustfmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo fmt --all --check && cd endsong_web && cargo fmt --all --check && cd ../endsong_ui && cargo fmt --all --check && cd endsong_macros && cargo fmt --all --check

  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo clippy -- --deny warnings && cd endsong_web && cargo clippy -- --deny warnings && cd ../endsong_ui && cargo clippy -- --deny warnings && cd endsong_macros && cargo clippy -- --deny warnings
